### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by AMDmi3** [MaxSavenkov/drdestructo2#1]
First, CMakeLists.txt reference nonexisting files (docs/Progress.txt). Next,

```
/tmp/drdestructo2/src/Game.cpp:438:6: error: use of undeclared identifier 'al_acknowledge_drawing_halt'
                                        al_acknowledge_drawing_halt( al_get_current_display() );
                                        ^
/tmp/drdestructo2/src/Game.cpp:444:6: error: use of undeclared identifier 'al_acknowledge_drawing_resume'
                                        al_acknowledge_drawing_resume( al_get_current_display() );
                                        ^
```

PS. The latter is probably caused by outdated allegro.

**Comment by MaxSavenkov** [comment]
Thank you, I removed the missing files from CMakeLists.txt.

al_acknowledge_drawing_halt and the other function should be available in 5.1.x branch, which is required to build this game.

**Comment by MaxSavenkov** [comment]
And fixed another error in CMake script... It should work now :)

**Comment by AMDmi3** [comment]
Thanks!
