### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by Mailaender** [MaxSavenkov/drdestructo2#3]
I plan to package it for @openSUSE and some kind of official reference point would be helpful although you already mentioned version 1.0 in https://github.com/MaxSavenkov/drdestructo2/commit/c16901b9c278f5c55e047dac404c386c19fa286a.

**Comment by MaxSavenkov** [comment]
I think you can try to package the latest master, since it's pretty much the final state of the game.

**Comment by Mailaender** [comment]
Then maybe tag that as 1.01 or something?

**Comment by MaxSavenkov** [comment]
Done
